config/routes.rb
CDevelop::Application.routes.draw do

  namespace :admin do
    resources :index do
      collection do
        get 'left'
        get 'top'
        get 'content' 
        get :main
      end

    end

    resources :notes

  end

end

app/models/note.rb
class  Note < ActiveRecord::Base

	attr_accessible	:title , :content	
end

app/controllers/admin/index_controller.rb
class Admin::IndexController < ApplicationController
  def login

  end

  def show
 	
  end

  def index
		information = 'Plase login '
		render :text => information 
  end


  def logout
  end

  def main
  	render :layout => false
  end

  def left

  end

  def top
  	
  end

  def content
  	
  end
end

app/controllers/admin/notes_controller.rb
class Admin::NotesController < ApplicationController

#	def index
#		@notes = Note.all
#	end

	def index
		respond_to do |format|
		  format.html # index.html.erb
		  #format.xml  { render :xml => Note.all }
		  
		  # With the Flexigrid, we need to render Json data
		  format.js do
		    # What is the first line of the result set we want ? (due to pagination. 0 = first)
		    offset = (params["page"].to_i-1)*params["rp"].to_i if params["page"] and params["rp"]

		    # Conditions passed by flexigrid
		    conditions = [params["qtype"]+"=?", params["query"]] if params["query"] and params["query"].strip!=""

		    notes = Note.where(conditions)

		    # Total count of lines, before paginating
		    total = notes.count

		    # notes from the page
		    notes_de_la_page = notes
		      .order([params["sortname"], params["sortorder"]].join(" "))
		      .offset(offset)
		      .limit(params["rp"]).all
		    
		    # Juste an ugly trick to add a bouton (button) method to the class, to use it in the Flexigrid
		    Note.class_eval do 
		      def bouton
		        %{<img src="images/close.png">}
		      end
		    end

		    # Rendering
		    render :json => {
		        :rows=>notes_de_la_page.collect{|r| {:id=>r.id, :cell=>{id: r.id,title: r.title} } } , 
		        :page=>params["page"],
		        :total=>total
		      }.to_json
		      
		  end #format.js
		  
		end #respond_to

	end #index method
	
	def show
		@note = Note.find(params[:id])
	end

	def edit
		@note = Note.find(params[:id])
	end

	def update
		@note = Note.find(params[:id])
		@note.update_attributes(params[:note])
		@note.save
		redirect_to note_url(@note)
	end

	def new
		@note = Note.new
	end

	def create
		Note.create(params[:note])
		redirect_to notes_url
	end

	def destroy
		@note.find(params[:id])
		@note.destroy
		redirect_to notes_url
	end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/admin/index_helper.rb
module Admin::IndexHelper
end

app/helpers/admin/notes_helper.rb
module Admin::NotesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/index/content.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
</head>

<body>
	<h2>欢迎登入 CBox 后台管理系统</h2>
</body>
</html>

app/views/admin/index/index.html.erb
<html>
	<head>
		<script type="text/javascript">
			function reVerify(){
				document.getElementById('rev').src="__CPUBLIC__/verify/demo.php/"+Math.random();
			}
		</script>		
	</head>
	<body>
		
		<div id="mian">
			<table border="0" cellspacing="5" cellpadding="5">
				<form action="__URL__/login/" method="post" accept-charset="utf-8">
					
				
					<label for="">用户名</label><input type="text" name="username" value="" id="">
					<label for="">密码</label><input type="password" name="password" value="" id="">
					验证码:<img src="__CPUBLIC__/verify/demo.php" id="rev" />
					<input type="text" name="verify" /><a  onClick="reVerify()">看不清</a>
					<input type="submit" name="submit" value="登陆" id="submit">
				</form>

			</table>
		</div>
		
	</body>
</html>

app/views/admin/index/left.html.erb
<!DOCTYPE html >
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>导航</title>

<%= content_for :action_name ,"admin/"+self.action_name %>
</head>

<body>
<div class="well" style="padding: 8px 0;">
        <ul class="nav nav-tabs nav-stacked"><!-- class="nav nav-list"> -->
          <li class="active"><a href="#"><i class="icon-home "></i> <strong>访友网</strong>内容管理</a></li>
			   <li><a href="__GROUP__/Member/index" target="mainFrame"><i class="icon-user"></i> 用户管理</a></li>
			   <li><a href="__GROUP__/Card/index" target="mainFrame"><i class="icon-book"></i> 名片管理</a></li>
			   <li><a href="__GROUP__/Message/index" target="mainFrame"><i class="icon-envelope"></i> 消息管理</a></li>
         <li><a href="/admin/notes" target="mainFrame"><i class="icon-pencil"></i> 笔记管理</a></li>
         <li><a href="__GROUP__/Photo/index" target="mainFrame"><i class="icon-picture"></i> 相册管理</a></li>
         <li><a href="__GROUP__/Category/index" target="mainFrame"><i class="icon-indent-left"></i> 分类管理</a></li>


        </ul>
      </div>
</body>
</html>

app/views/admin/index/login.html.erb
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>访友网|后台管理</title>
<link href="__CPUBLIC__/css/bootstrap.css" rel="stylesheet" type="text/css" />
		<script type="text/javascript">
			function reVerify(){
				document.getElementById('rev').src="__CPUBLIC__/verify/demo.php/"+Math.random();
			}
		</script>	
<style>
body{
		background:#122d5c;
	}
	
	#body{
		margin-top:50px;
	}
	.main{
		float:left;
		width:200px;
		margin-top:100px;
		margin-left:50px;
	}
	p{
		color:#FFF;
	}
	.seal{
		float:left;
		margin-top:200px;
		margin-left:400px;
		margin-right:100px;
	}
	.cut{
		float:left;
		margin-top:70px;
		margin-left:20;
	}
	h1 {
		color:#FFF;
	}
	#title{
		float:left;
		margin-left:200px;
		margin-top:200px;
	}
</style>
</head>

<body>
	<div id="body">
		
	
	 	<div class="seal" class="float_r">
	 		<img src="__CPUBLIC__/images/mylogo.png" />
	 		<h1>网后台登陆</h1>
	 	</div>
	 	<div class="cut">
	 		<img src="__CPUBLIC__/images/cut.png" />
	 	</div>
	    <div class="main">
	        <form method="post" action="__URL__/login/">
	            <label for="email_box"><p>用户名:</p></label><input id="email_box" type="text" class="input-medium" placeholder="Name" name="username" >
	            <label for="password_box"><p>密码:</p></label><input id="password_box" type="password" class="input-medium" placeholder="Password" name="password">
	            <label class="checkbox">
	                <input type="checkbox"> <p>记住我</p>
	            </label>
	            <input type="text" class="input-small" name="verify" placeholder="验证">&nbsp;<a href="#" onClick="reVerify()">看不清</a>
	            <p><img src="__CPUBLIC__/verify/demo.php" id="rev" /></p>
	            
	            <button type="submit" class="btn btn-primary btn-large" target="#">登陆</button>
	        </form>
	    </div>
	</div>	
</body>
</html>

app/views/admin/index/main.html.erb
<!DOCTYPE html>
<html >
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>后台管理</title>

</head>
<frameset rows="139,*" cols="*" frameborder="1" border="5" framespacing="0" >
	
  <frame src="/admin/index/top" name="topFrame" scrolling="No" noresize="noresize" id="topFrame" title="topFrame"    />
  
  <frameset rows="*" cols="210,*" framespacing="0" frameborder="1" border="5">
  
    <frame src="/admin/index/left" name="leftFrame" scrolling="No" noresize="noresize" id="leftFrame" title="leftFrame" />
    
   <frame src="/admin/index/content" name="mainFrame" id="mainFrame" title="contentFrame" />
    
  </frameset>
  
</frameset>
<noframes>
	<body>
		sss
	</body>
</noframes>
</html>

app/views/admin/index/top.html.erb
<!DOCTYPE html>
<html >
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>无标题文档</title>


<%= content_for :action_name ,"admin/"+self.action_name %>
</head>

<body>
	<div id="admin">
		欢迎<%= self.action_name %>管理员
		<a href="__GROUP__/Index/logout">登出</a>
	</div>	
	<h1>访友网管理</h1>
	<div style="clear:both"></div>
    <div>
    	<ul class="top-menu">
        	<li>
            	<a href="__GROUP__/Setting/index" target="mainFrame">网站配置管理</a>
            </li>
        	<li>
            	<a href="__GROUP__/Administrator/index" target="mainFrame">管理员管理</a>
            </li>            
        </ul>
    </div>
</body>
</html>

app/views/admin/notes/index.html.erb
<div id="content">
	<!--<div class="title">笔记管理</div>-->
	<div class="data">
	<table class="flex1"></table>
	<script type="text/javascript">

		$(".flex1").flexigrid(
			{
			method: 'GET',
			url: 'notes.js',
			dataType: 'json',
			colModel : [
				{display: '笔记编码', name : 'id', width : 140, sortable : true, align: 'left'},
				{display: '标题', name : 'title', width : 180, sortable : true, align: 'conter'},
				],
			searchitems : [
				{display: 'id', name : 'title', isdefault: true}
				],
			button: [
				{ name: '修改', bclass: 'edit', onpress: Edit }
			],
			singleSelect: true,
			sortname: "title",
			sortorder: "asc",
			usepager: true,
			title: '笔记管理',
			rp: 10,
			//pagestat: "Affichage des lignes {from} à {to} sur {total}",
			showTableToggleBtn: true,
    		// width: 700, ==> auto par défaut
			height: 400,
			//findtext: 'Chercher',
			//procmsg: 'En cours, veuillez patienter...',
			//nomsg: 'Aucun résultat',
			//outof: 'sur'
			useRp : true,
			}
		);

		function Edit () {
			alert('Edit');
		}
	</script>
	<script type="text/javascript">
		$(document).ready(function  () {
			//alert('se');
			$('.flex1').click(function  () {
				//alert('se')
				id = $('.flex1 .trSelected').find("td").eq(0).text();
				alert(id);
			});
		});
	</script>
	</div>
	
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield :title %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag yield :action_name %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/notes/_form.html.erb
<%= form_for @note, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :content, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :content, :class => 'text_area' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                notes_path, :class => 'btn' %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<%- model_class = Note -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/notes/index.html.erb
<%- model_class = Note -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:content) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= link_to note.id, note_path(note) %></td>
        <td><%= note.title %></td>
        <td><%= note.content %></td>
        <td><%=l note.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_note_path(note), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      note_path(note),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_note_path,
            :class => 'btn btn-primary' %>

app/views/notes/new.html.erb
<%- model_class = Note -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/notes/show.html.erb
<%- model_class = Note -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @note.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:content) %>:</strong></dt>
  <dd><%= @note.content %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              notes_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_note_path(@note), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              note_path(@note),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>